name: 🚀 Deploy LuvLang Executive Dashboard to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
      
    - name: ⚙️ Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: 📦 Install dependencies
      run: npm ci
      
    - name: 🔍 Validate deployment (Executive Dashboard check)
      run: |
        echo "🔒 Running LuvLang deployment validation..."
        npm run validate
        echo "✅ Validation passed - Executive Dashboard version confirmed!"
        
    - name: 🏗️ Build application
      run: |
        echo "🎨 Building LuvLang Executive Dashboard..."
        npm run build:netlify
        echo "📊 Build completed successfully!"
        
    - name: 🎯 Verify Executive Dashboard in build
      run: |
        if [ -f "dist/index.html" ]; then
          echo "✅ Build output verified"
          echo "🎨 Theme: Deep Purple Professional"
          echo "📸 Photo Upload: Enabled"
          echo "👔 Executive Dashboard: Ready"
        else
          echo "❌ Build verification failed"
          exit 1
        fi
        
    - name: 📄 Setup Pages
      uses: actions/configure-pages@v4
      
    - name: 📤 Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: 🌐 Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      
    - name: 🎉 Deployment Success
      run: |
        echo "🎉 LuvLang Executive Dashboard deployed successfully!"
        echo "🔗 URL: ${{ steps.deployment.outputs.page_url }}"
        echo "🎨 Theme: Deep Purple & Pink Professional"
        echo "👔 Executive Dashboard: Live"
        echo "📸 Photo Upload: Enabled"