name: Deploy to Netlify

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger Netlify Deploy
      run: |
        curl -X POST -d {} https://api.netlify.com/build_hooks/68a77d3fdd94c010896d3f07