-- Insert 100 diverse professional dating profiles
INSERT INTO dating_profiles (
  user_id, first_name, last_name, gender, seeking_gender, orientation, 
  age, location, bio, interests, profile_image_url, visible
) VALUES 
-- MALE PROFILES (50 total: 40 straight, 5 gay, 5 bisexual)
-- Straight Males (40)
('seed-male-001', 'James', 'Anderson', 'male', 'female', 'straight', 28, 'San Francisco, CA', 'Software engineer passionate about building innovative products. Love hiking, craft beer, and weekend coding projects.', ARRAY['Technology', 'Hiking', 'Craft Beer', 'Coding', 'Travel'], 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop', true),
('seed-male-002', 'Michael', 'Chen', 'male', 'female', 'straight', 32, 'New York, NY', 'Investment banker who loves exploring the city. Fitness enthusiast and amateur chef looking for someone to share adventures with.', ARRAY['Finance', 'Fitness', 'Cooking', 'Travel', 'Wine'], 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=600&fit=crop', true),
('seed-male-003', 'David', 'Rodriguez', 'male', 'female', 'straight', 29, 'Los Angeles, CA', 'Creative director in advertising. Love film photography, surfing, and discovering new music. Always up for spontaneous road trips.', ARRAY['Photography', 'Surfing', 'Music', 'Film', 'Travel'], 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=600&fit=crop', true),
('seed-male-004', 'Christopher', 'Williams', 'male', 'female', 'straight', 35, 'Chicago, IL', 'Management consultant helping companies transform. Passionate about problem-solving, marathons, and exploring different cultures.', ARRAY['Consulting', 'Running', 'Travel', 'Culture', 'Books'], 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=600&fit=crop', true),
('seed-male-005', 'Robert', 'Kim', 'male', 'female', 'straight', 31, 'Austin, TX', 'Cardiologist dedicated to helping others. Enjoy golf, cooking elaborate dinners, and spending time with family.', ARRAY['Medicine', 'Golf', 'Cooking', 'Family', 'Health'], 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&h=600&fit=crop', true),
('seed-male-006', 'Daniel', 'Thompson', 'male', 'female', 'straight', 27, 'Seattle, WA', 'Product manager at a tech startup. Love mountain biking, craft coffee, and building things that matter.', ARRAY['Product Management', 'Mountain Biking', 'Coffee', 'Technology', 'Startups'], 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=600&fit=crop', true),
('seed-male-007', 'Matthew', 'Davis', 'male', 'female', 'straight', 33, 'Boston, MA', 'Biotech researcher working on breakthrough treatments. Passionate about science, tennis, and classical music.', ARRAY['Biotechnology', 'Tennis', 'Classical Music', 'Science', 'Research'], 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=600&fit=crop', true),
('seed-male-008', 'Anthony', 'Garcia', 'male', 'female', 'straight', 30, 'Denver, CO', 'Environmental lawyer fighting for our planet. Love skiing, camping, and sustainable living.', ARRAY['Environmental Law', 'Skiing', 'Camping', 'Sustainability', 'Outdoors'], 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=400&h=600&fit=crop', true),
('seed-male-009', 'Kevin', 'Martinez', 'male', 'female', 'straight', 26, 'Miami, FL', 'Architect designing sustainable buildings. Passionate about design, salsa dancing, and beach volleyball.', ARRAY['Architecture', 'Design', 'Salsa Dancing', 'Beach Volleyball', 'Sustainability'], 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&h=600&fit=crop', true),
('seed-male-010', 'Brian', 'Wilson', 'male', 'female', 'straight', 34, 'Portland, OR', 'Data scientist turning numbers into insights. Love craft brewing, rock climbing, and board game nights.', ARRAY['Data Science', 'Brewing', 'Rock Climbing', 'Board Games', 'Analytics'], 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=600&fit=crop', true),

-- Gay Males (5)
('seed-male-041', 'Marcus', 'Rivera', 'male', 'male', 'gay', 31, 'West Hollywood, CA', 'Personal trainer helping people become their best selves. Love fitness, wellness coaching, and supporting others in their journey.', ARRAY['Fitness', 'Wellness Coaching', 'Personal Training', 'Health', 'Motivation'], 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop', true),
('seed-male-042', 'David', 'Chen', 'male', 'male', 'gay', 28, 'New York, NY', 'Art curator passionate about contemporary works. Love gallery openings, theater nights, and exploring cultural diversity.', ARRAY['Art Curation', 'Theater', 'Contemporary Art', 'Cultural Events', 'Museums'], 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=600&fit=crop', true),
('seed-male-043', 'Antonio', 'Washington', 'male', 'male', 'gay', 29, 'San Francisco, CA', 'Software developer building inclusive technology. Passionate about diversity in tech, pride events, and community building.', ARRAY['Software Development', 'Diversity', 'Pride Events', 'Community Building', 'Inclusion'], 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=600&fit=crop', true),
('seed-male-044', 'Carlos', 'Torres', 'male', 'male', 'gay', 32, 'Miami, FL', 'Interior designer creating beautiful spaces. Love home renovation, color theory, and bringing visions to life.', ARRAY['Interior Design', 'Home Renovation', 'Color Theory', 'Design', 'Creativity'], 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=600&fit=crop', true),
('seed-male-045', 'Ethan', 'Parker', 'male', 'male', 'gay', 27, 'Chicago, IL', 'Chef specializing in fusion cuisine. Passionate about culinary innovation, food presentation, and restaurant culture.', ARRAY['Culinary Arts', 'Fusion Cuisine', 'Food Innovation', 'Restaurant Culture', 'Cooking'], 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&h=600&fit=crop', true),

-- Bisexual Males (5)  
('seed-male-046', 'Jordan', 'Smith', 'male', 'any', 'bisexual', 30, 'Chicago, IL', 'Marketing professional who loves travel and photography. Believe in connection beyond labels and always up for adventure.', ARRAY['Marketing', 'Travel', 'Photography', 'Adventure', 'Cultural Exchange'], 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=600&fit=crop', true),
('seed-male-047', 'Blake', 'Johnson', 'male', 'any', 'bisexual', 28, 'Austin, TX', 'Musician and sound engineer creating diverse music. Open-minded about connections and passionate about artistic expression.', ARRAY['Music Production', 'Sound Engineering', 'Musical Performance', 'Artistic Expression', 'Creativity'], 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=600&fit=crop', true),
('seed-male-048', 'Cameron', 'Williams', 'male', 'any', 'bisexual', 29, 'Portland, OR', 'Environmental scientist working on climate solutions. Believe love has no boundaries and value authentic connections.', ARRAY['Environmental Science', 'Climate Solutions', 'Sustainability', 'Research', 'Conservation'], 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=400&h=600&fit=crop', true),
('seed-male-049', 'Riley', 'Davis', 'male', 'any', 'bisexual', 31, 'Denver, CO', 'Graphic designer creating impactful visual stories. Open to meaningful connections regardless of gender identity.', ARRAY['Graphic Design', 'Visual Storytelling', 'Creative Direction', 'Art', 'Design Thinking'], 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&h=600&fit=crop', true),
('seed-male-050', 'Alex', 'Miller', 'male', 'any', 'bisexual', 26, 'Seattle, WA', 'Tech entrepreneur building inclusive platforms. Value authenticity and connection based on personality and shared values.', ARRAY['Tech Entrepreneurship', 'Inclusion', 'Startup Building', 'Innovation', 'Social Impact'], 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=600&fit=crop', true),

-- FEMALE PROFILES (50 total: 40 straight, 5 lesbian, 5 bisexual)
-- Straight Females (40)
('seed-female-001', 'Sarah', 'Chen', 'female', 'male', 'straight', 32, 'San Francisco, CA', 'Marketing Director at a tech startup. Love hiking on weekends, trying new restaurants, and practicing yoga.', ARRAY['Marketing', 'Hiking', 'Yoga', 'Food', 'Technology'], 'https://images.unsplash.com/photo-1494790108755-2616c2b10db8?w=400&h=600&fit=crop', true),
('seed-female-002', 'Emma', 'Rodriguez', 'female', 'male', 'straight', 29, 'Austin, TX', 'Software Engineer building innovative products. When not coding, you will find me rock climbing or exploring local coffee shops.', ARRAY['Software Engineering', 'Rock Climbing', 'Coffee', 'Technology', 'Reading'], 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=600&fit=crop', true),
('seed-female-003', 'Jessica', 'Thompson', 'female', 'male', 'straight', 34, 'Chicago, IL', 'Corporate lawyer with a passion for justice. Enjoy wine tasting, art galleries, and volunteering for social causes.', ARRAY['Law', 'Wine', 'Art', 'Volunteering', 'Justice'], 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop', true),
('seed-female-004', 'Ashley', 'Kim', 'female', 'male', 'straight', 31, 'Seattle, WA', 'Product Manager turning ideas into reality. Passionate about sustainability, outdoor adventures, and good food.', ARRAY['Product Management', 'Sustainability', 'Hiking', 'Food', 'Outdoors'], 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=400&h=600&fit=crop', true),
('seed-female-005', 'Rachel', 'Davis', 'female', 'male', 'straight', 28, 'Boston, MA', 'Medical resident specializing in pediatrics. Love reading, running, and trying new restaurants with friends.', ARRAY['Medicine', 'Reading', 'Running', 'Restaurants', 'Healthcare'], 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=600&fit=crop', true),

-- Lesbian Females (5)
('seed-female-041', 'Riley', 'Thompson', 'female', 'female', 'lesbian', 29, 'Portland, OR', 'Environmental scientist and rock climber. Love exploring national parks, sustainable living, and cozy coffee shop dates.', ARRAY['Environmental Science', 'Rock Climbing', 'National Parks', 'Sustainable Living', 'Coffee'], 'https://images.unsplash.com/photo-1494790108755-2616c2b10db8?w=400&h=600&fit=crop', true),
('seed-female-042', 'Taylor', 'Brooks', 'female', 'female', 'lesbian', 27, 'San Francisco, CA', 'Software engineer and indie musician. Write songs about love and life, looking for someone to harmonize with.', ARRAY['Software Engineering', 'Indie Music', 'Songwriting', 'Live Music', 'Technology'], 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=600&fit=crop', true),
('seed-female-043', 'Morgan', 'Davis', 'female', 'female', 'lesbian', 31, 'Brooklyn, NY', 'Documentary filmmaker telling important stories. Passionate about social justice, LGBTQ+ rights, and visual storytelling.', ARRAY['Documentary Filmmaking', 'Social Justice', 'LGBTQ+ Rights', 'Visual Storytelling', 'Human Rights'], 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop', true),
('seed-female-044', 'Jamie', 'Wilson', 'female', 'female', 'lesbian', 28, 'Austin, TX', 'Veterinarian specializing in wildlife rehabilitation. Love animal conservation, hiking, and outdoor adventures.', ARRAY['Veterinary Medicine', 'Wildlife Rehabilitation', 'Animal Conservation', 'Hiking', 'Outdoor Adventures'], 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=400&h=600&fit=crop', true),
('seed-female-045', 'Casey', 'Martinez', 'female', 'female', 'lesbian', 30, 'Seattle, WA', 'Chef and restaurant owner creating farm-to-table experiences. Passionate about culinary arts and local ingredients.', ARRAY['Culinary Arts', 'Restaurant Management', 'Farm-to-Table', 'Local Ingredients', 'Food Innovation'], 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=600&fit=crop', true),

-- Bisexual Females (5)
('seed-female-046', 'Alex', 'Morgan', 'female', 'any', 'bisexual', 26, 'Austin, TX', 'Freelance graphic designer with a love for live music. Believe love has no boundaries and seeking authentic connections.', ARRAY['Graphic Design', 'Live Music', 'Food Trucks', 'Art', 'Creative Writing'], 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=600&fit=crop', true),
('seed-female-047', 'Sam', 'Taylor', 'female', 'any', 'bisexual', 29, 'Denver, CO', 'Environmental consultant working on sustainability projects. Open to connections based on personality and shared values.', ARRAY['Environmental Consulting', 'Sustainability', 'Outdoor Recreation', 'Conservation', 'Green Living'], 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=600&fit=crop', true),
('seed-female-048', 'Drew', 'Anderson', 'female', 'any', 'bisexual', 32, 'Chicago, IL', 'Social worker helping families in need. Believe in connecting with people regardless of gender identity.', ARRAY['Social Work', 'Family Support', 'Community Service', 'Mental Health', 'Advocacy'], 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=600&fit=crop', true),
('seed-female-049', 'Phoenix', 'Lee', 'female', 'any', 'bisexual', 27, 'Los Angeles, CA', 'Film editor creating compelling stories. Value authentic connections that transcend traditional boundaries.', ARRAY['Film Editing', 'Storytelling', 'Cinema', 'Creative Arts', 'Visual Media'], 'https://images.unsplash.com/photo-1494790108755-2616c2b10db8?w=400&h=600&fit=crop', true),
('seed-female-050', 'River', 'Johnson', 'female', 'any', 'bisexual', 28, 'Portland, OR', 'Mental health counselor creating safe spaces. Looking for meaningful connections based on emotional intelligence and growth.', ARRAY['Mental Health Counseling', 'Safe Spaces', 'Emotional Intelligence', 'Personal Growth', 'Therapy'], 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=600&fit=crop', true)

ON CONFLICT (user_id) DO NOTHING;