-- Insert 100 diverse professional dating profiles with proper UUIDs
INSERT INTO dating_profiles (
  user_id, first_name, last_name, gender, seeking_gender, orientation, 
  age, location, bio, interests, profile_image_url, visible
) VALUES 
-- MALE PROFILES (50 total: 40 straight, 5 gay, 5 bisexual)
-- Straight Males (40)
(gen_random_uuid(), 'James', 'Anderson', 'male', 'female', 'straight', 28, 'San Francisco, CA', 'Software engineer passionate about building innovative products. Love hiking, craft beer, and weekend coding projects.', ARRAY['Technology', 'Hiking', 'Craft Beer', 'Coding', 'Travel'], 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Michael', 'Chen', 'male', 'female', 'straight', 32, 'New York, NY', 'Investment banker who loves exploring the city. Fitness enthusiast and amateur chef looking for someone to share adventures with.', ARRAY['Finance', 'Fitness', 'Cooking', 'Travel', 'Wine'], 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'David', 'Rodriguez', 'male', 'female', 'straight', 29, 'Los Angeles, CA', 'Creative director in advertising. Love film photography, surfing, and discovering new music. Always up for spontaneous road trips.', ARRAY['Photography', 'Surfing', 'Music', 'Film', 'Travel'], 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Christopher', 'Williams', 'male', 'female', 'straight', 35, 'Chicago, IL', 'Management consultant helping companies transform. Passionate about problem-solving, marathons, and exploring different cultures.', ARRAY['Consulting', 'Running', 'Travel', 'Culture', 'Books'], 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Robert', 'Kim', 'male', 'female', 'straight', 31, 'Austin, TX', 'Cardiologist dedicated to helping others. Enjoy golf, cooking elaborate dinners, and spending time with family.', ARRAY['Medicine', 'Golf', 'Cooking', 'Family', 'Health'], 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Daniel', 'Thompson', 'male', 'female', 'straight', 27, 'Seattle, WA', 'Product manager at a tech startup. Love mountain biking, craft coffee, and building things that matter.', ARRAY['Product Management', 'Mountain Biking', 'Coffee', 'Technology', 'Startups'], 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Matthew', 'Davis', 'male', 'female', 'straight', 33, 'Boston, MA', 'Biotech researcher working on breakthrough treatments. Passionate about science, tennis, and classical music.', ARRAY['Biotechnology', 'Tennis', 'Classical Music', 'Science', 'Research'], 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Anthony', 'Garcia', 'male', 'female', 'straight', 30, 'Denver, CO', 'Environmental lawyer fighting for our planet. Love skiing, camping, and sustainable living.', ARRAY['Environmental Law', 'Skiing', 'Camping', 'Sustainability', 'Outdoors'], 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Kevin', 'Martinez', 'male', 'female', 'straight', 26, 'Miami, FL', 'Architect designing sustainable buildings. Passionate about design, salsa dancing, and beach volleyball.', ARRAY['Architecture', 'Design', 'Salsa Dancing', 'Beach Volleyball', 'Sustainability'], 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Brian', 'Wilson', 'male', 'female', 'straight', 34, 'Portland, OR', 'Data scientist turning numbers into insights. Love craft brewing, rock climbing, and board game nights.', ARRAY['Data Science', 'Brewing', 'Rock Climbing', 'Board Games', 'Analytics'], 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Steven', 'Brown', 'male', 'female', 'straight', 28, 'Nashville, TN', 'Music producer working with indie artists. Guitar player who loves live music and creative collaboration.', ARRAY['Music Production', 'Guitar', 'Live Music', 'Creativity', 'Collaboration'], 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Andrew', 'Jones', 'male', 'female', 'straight', 29, 'Phoenix, AZ', 'Physical therapist helping athletes recover. Love hiking desert trails, CrossFit, and healthy cooking.', ARRAY['Physical Therapy', 'Hiking', 'CrossFit', 'Healthy Cooking', 'Sports Medicine'], 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Joshua', 'Miller', 'male', 'female', 'straight', 31, 'Atlanta, GA', 'Marketing executive in the gaming industry. Passionate about esports, strategy games, and tech innovation.', ARRAY['Marketing', 'Gaming', 'Esports', 'Strategy', 'Technology'], 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Ryan', 'Taylor', 'male', 'female', 'straight', 32, 'San Diego, CA', 'Marine biologist studying ocean conservation. Love scuba diving, beach runs, and environmental activism.', ARRAY['Marine Biology', 'Scuba Diving', 'Running', 'Conservation', 'Ocean'], 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Nicholas', 'Anderson', 'male', 'female', 'straight', 27, 'Washington, DC', 'Policy analyst working on healthcare reform. Enjoy political discussions, tennis, and trying new restaurants.', ARRAY['Policy Analysis', 'Healthcare', 'Politics', 'Tennis', 'Food'], 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Tyler', 'Moore', 'male', 'female', 'straight', 30, 'Minneapolis, MN', 'Renewable energy engineer building a cleaner future. Love winter sports, craft beer, and sustainability projects.', ARRAY['Renewable Energy', 'Winter Sports', 'Craft Beer', 'Sustainability', 'Engineering'], 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Jonathan', 'White', 'male', 'female', 'straight', 33, 'Philadelphia, PA', 'Emergency room physician saving lives daily. Passionate about medicine, marathon running, and volunteer work.', ARRAY['Emergency Medicine', 'Marathon Running', 'Volunteering', 'Healthcare', 'Fitness'], 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Aaron', 'Harris', 'male', 'female', 'straight', 28, 'Salt Lake City, UT', 'UX designer creating user-friendly experiences. Love mountain hiking, photography, and design thinking workshops.', ARRAY['UX Design', 'Hiking', 'Photography', 'Design Thinking', 'User Experience'], 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Justin', 'Clark', 'male', 'female', 'straight', 29, 'Raleigh, NC', 'Veterinarian caring for animals. Passionate about animal welfare, hiking with my rescue dog, and outdoor adventures.', ARRAY['Veterinary Medicine', 'Animal Welfare', 'Hiking', 'Dogs', 'Outdoors'], 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Benjamin', 'Lewis', 'male', 'female', 'straight', 31, 'Richmond, VA', 'Financial advisor helping families plan their future. Enjoy investment research, golf, and family gatherings.', ARRAY['Financial Planning', 'Investment', 'Golf', 'Family', 'Financial Security'], 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Samuel', 'Robinson', 'male', 'female', 'straight', 26, 'Kansas City, MO', 'Cybersecurity analyst protecting digital infrastructure. Love puzzle solving, chess, and staying ahead of threats.', ARRAY['Cybersecurity', 'Puzzle Solving', 'Chess', 'Technology', 'Problem Solving'], 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Gregory', 'Walker', 'male', 'female', 'straight', 34, 'Indianapolis, IN', 'Manufacturing engineer optimizing production systems. Passionate about efficiency, motorsports, and innovation.', ARRAY['Manufacturing', 'Engineering', 'Motorsports', 'Innovation', 'Efficiency'], 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Alexander', 'Hall', 'male', 'female', 'straight', 30, 'Columbus, OH', 'Digital marketing strategist growing online brands. Love data analysis, content creation, and social media trends.', ARRAY['Digital Marketing', 'Data Analysis', 'Content Creation', 'Social Media', 'Brand Strategy'], 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Patrick', 'Allen', 'male', 'female', 'straight', 32, 'Charlotte, NC', 'Real estate developer creating sustainable communities. Enjoy urban planning, cycling, and community engagement.', ARRAY['Real Estate', 'Urban Planning', 'Cycling', 'Community Development', 'Sustainability'], 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Jason', 'Young', 'male', 'female', 'straight', 28, 'Jacksonville, FL', 'Aerospace engineer working on next-gen aircraft. Passionate about aviation, flying small planes, and space exploration.', ARRAY['Aerospace Engineering', 'Aviation', 'Flying', 'Space Exploration', 'Technology'], 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Mark', 'Hernandez', 'male', 'female', 'straight', 35, 'Memphis, TN', 'Restaurant owner serving authentic cuisine. Love culinary innovation, wine tasting, and bringing people together through food.', ARRAY['Culinary Arts', 'Restaurant Management', 'Wine', 'Food Innovation', 'Hospitality'], 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Eric', 'King', 'male', 'female', 'straight', 29, 'Louisville, KY', 'Sports journalist covering professional athletics. Passionate about storytelling, basketball, and behind-the-scenes access.', ARRAY['Sports Journalism', 'Storytelling', 'Basketball', 'Writing', 'Sports'], 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Kenneth', 'Wright', 'male', 'female', 'straight', 31, 'Oklahoma City, OK', 'Oil and gas engineer optimizing energy production. Love outdoor adventures, fishing, and energy innovation.', ARRAY['Energy Engineering', 'Fishing', 'Outdoors', 'Innovation', 'Energy Production'], 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Paul', 'Lopez', 'male', 'female', 'straight', 27, 'Las Vegas, NV', 'Hospitality manager at luxury resorts. Passionate about customer service, travel experiences, and event planning.', ARRAY['Hospitality Management', 'Customer Service', 'Travel', 'Event Planning', 'Luxury Services'], 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Edward', 'Hill', 'male', 'female', 'straight', 33, 'Baltimore, MD', 'Pharmaceutical researcher developing new treatments. Love scientific discovery, lab work, and improving human health.', ARRAY['Pharmaceutical Research', 'Science', 'Laboratory Work', 'Medical Innovation', 'Health'], 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Douglas', 'Scott', 'male', 'female', 'straight', 30, 'Birmingham, AL', 'Civil engineer building infrastructure for the future. Passionate about construction, project management, and community development.', ARRAY['Civil Engineering', 'Construction', 'Project Management', 'Infrastructure', 'Community Development'], 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Peter', 'Green', 'male', 'female', 'straight', 28, 'Buffalo, NY', 'Mechanical engineer designing automated systems. Love robotics, 3D printing, and solving complex engineering problems.', ARRAY['Mechanical Engineering', 'Robotics', '3D Printing', 'Automation', 'Problem Solving'], 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Adam', 'Adams', 'male', 'female', 'straight', 32, 'New Orleans, LA', 'Jazz musician and music teacher sharing the gift of music. Passionate about jazz history, live performance, and musical education.', ARRAY['Jazz Music', 'Music Education', 'Live Performance', 'Music History', 'Teaching'], 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Nathan', 'Baker', 'male', 'female', 'straight', 29, 'Tucson, AZ', 'Desert ecologist studying climate adaptation. Love nature photography, desert hiking, and environmental conservation.', ARRAY['Ecology', 'Nature Photography', 'Desert Hiking', 'Climate Science', 'Conservation'], 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Henry', 'Gonzalez', 'male', 'female', 'straight', 31, 'Albuquerque, NM', 'Renewable energy consultant helping businesses go green. Passionate about solar technology, hiking, and sustainable living.', ARRAY['Renewable Energy', 'Solar Technology', 'Hiking', 'Sustainability', 'Green Business'], 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Walter', 'Nelson', 'male', 'female', 'straight', 26, 'Spokane, WA', 'Forest ranger protecting our natural resources. Love wilderness camping, wildlife photography, and outdoor education.', ARRAY['Forest Management', 'Camping', 'Wildlife Photography', 'Outdoor Education', 'Conservation'], 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Jack', 'Carter', 'male', 'female', 'straight', 34, 'Boise, ID', 'Agricultural engineer improving farming efficiency. Passionate about sustainable agriculture, farm technology, and food security.', ARRAY['Agricultural Engineering', 'Sustainable Agriculture', 'Farm Technology', 'Food Security', 'Rural Development'], 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Arthur', 'Mitchell', 'male', 'female', 'straight', 33, 'Madison, WI', 'Cheese maker creating artisanal dairy products. Love traditional techniques, farm-to-table dining, and culinary craftsmanship.', ARRAY['Cheese Making', 'Artisanal Food', 'Farm-to-Table', 'Culinary Arts', 'Traditional Crafts'], 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Harold', 'Perez', 'male', 'female', 'straight', 27, 'Des Moines, IA', 'Insurance analyst helping families protect their future. Passionate about risk assessment, family values, and financial security.', ARRAY['Insurance Analysis', 'Risk Assessment', 'Family Values', 'Financial Security', 'Protection Planning'], 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Gerald', 'Roberts', 'male', 'female', 'straight', 30, 'Little Rock, AR', 'Agricultural researcher developing drought-resistant crops. Love plant science, greenhouse work, and sustainable farming.', ARRAY['Agricultural Research', 'Plant Science', 'Greenhouse Management', 'Sustainable Farming', 'Crop Development'], 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=600&fit=crop', true),

-- Gay Males (5)
(gen_random_uuid(), 'Marcus', 'Rivera', 'male', 'male', 'gay', 31, 'West Hollywood, CA', 'Personal trainer helping people become their best selves. Love fitness, wellness coaching, and supporting others in their journey.', ARRAY['Fitness', 'Wellness Coaching', 'Personal Training', 'Health', 'Motivation'], 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'David', 'Chen', 'male', 'male', 'gay', 28, 'New York, NY', 'Art curator passionate about contemporary works. Love gallery openings, theater nights, and exploring cultural diversity.', ARRAY['Art Curation', 'Theater', 'Contemporary Art', 'Cultural Events', 'Museums'], 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Antonio', 'Washington', 'male', 'male', 'gay', 29, 'San Francisco, CA', 'Software developer building inclusive technology. Passionate about diversity in tech, pride events, and community building.', ARRAY['Software Development', 'Diversity', 'Pride Events', 'Community Building', 'Inclusion'], 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Carlos', 'Torres', 'male', 'male', 'gay', 32, 'Miami, FL', 'Interior designer creating beautiful spaces. Love home renovation, color theory, and bringing visions to life.', ARRAY['Interior Design', 'Home Renovation', 'Color Theory', 'Design', 'Creativity'], 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Ethan', 'Parker', 'male', 'male', 'gay', 27, 'Chicago, IL', 'Chef specializing in fusion cuisine. Passionate about culinary innovation, food presentation, and restaurant culture.', ARRAY['Culinary Arts', 'Fusion Cuisine', 'Food Innovation', 'Restaurant Culture', 'Cooking'], 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&h=600&fit=crop', true),

-- Bisexual Males (5)  
(gen_random_uuid(), 'Jordan', 'Smith', 'male', 'any', 'bisexual', 30, 'Chicago, IL', 'Marketing professional who loves travel and photography. Believe in connection beyond labels and always up for adventure.', ARRAY['Marketing', 'Travel', 'Photography', 'Adventure', 'Cultural Exchange'], 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Blake', 'Johnson', 'male', 'any', 'bisexual', 28, 'Austin, TX', 'Musician and sound engineer creating diverse music. Open-minded about connections and passionate about artistic expression.', ARRAY['Music Production', 'Sound Engineering', 'Musical Performance', 'Artistic Expression', 'Creativity'], 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Cameron', 'Williams', 'male', 'any', 'bisexual', 29, 'Portland, OR', 'Environmental scientist working on climate solutions. Believe love has no boundaries and value authentic connections.', ARRAY['Environmental Science', 'Climate Solutions', 'Sustainability', 'Research', 'Conservation'], 'https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Riley', 'Davis', 'male', 'any', 'bisexual', 31, 'Denver, CO', 'Graphic designer creating impactful visual stories. Open to meaningful connections regardless of gender identity.', ARRAY['Graphic Design', 'Visual Storytelling', 'Creative Direction', 'Art', 'Design Thinking'], 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Alex', 'Miller', 'male', 'any', 'bisexual', 26, 'Seattle, WA', 'Tech entrepreneur building inclusive platforms. Value authenticity and connection based on personality and shared values.', ARRAY['Tech Entrepreneurship', 'Inclusion', 'Startup Building', 'Innovation', 'Social Impact'], 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=600&fit=crop', true),

-- FEMALE PROFILES (50 total: 40 straight, 5 lesbian, 5 bisexual)
-- Straight Females (40)
(gen_random_uuid(), 'Sarah', 'Chen', 'female', 'male', 'straight', 32, 'San Francisco, CA', 'Marketing Director at a tech startup. Love hiking on weekends, trying new restaurants, and practicing yoga.', ARRAY['Marketing', 'Hiking', 'Yoga', 'Food', 'Technology'], 'https://images.unsplash.com/photo-1494790108755-2616c2b10db8?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Emma', 'Rodriguez', 'female', 'male', 'straight', 29, 'Austin, TX', 'Software Engineer building innovative products. When not coding, you will find me rock climbing or exploring local coffee shops.', ARRAY['Software Engineering', 'Rock Climbing', 'Coffee', 'Technology', 'Reading'], 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Jessica', 'Thompson', 'female', 'male', 'straight', 34, 'Chicago, IL', 'Corporate lawyer with a passion for justice. Enjoy wine tasting, art galleries, and volunteering for social causes.', ARRAY['Law', 'Wine', 'Art', 'Volunteering', 'Justice'], 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Ashley', 'Kim', 'female', 'male', 'straight', 31, 'Seattle, WA', 'Product Manager turning ideas into reality. Passionate about sustainability, outdoor adventures, and good food.', ARRAY['Product Management', 'Sustainability', 'Hiking', 'Food', 'Outdoors'], 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Rachel', 'Davis', 'female', 'male', 'straight', 28, 'Boston, MA', 'Medical resident specializing in pediatrics. Love reading, running, and trying new restaurants with friends.', ARRAY['Medicine', 'Reading', 'Running', 'Restaurants', 'Healthcare'], 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Lauren', 'Wilson', 'female', 'male', 'straight', 30, 'Los Angeles, CA', 'Film producer creating meaningful stories. Passionate about cinema, travel documentaries, and cultural exploration.', ARRAY['Film Production', 'Cinema', 'Travel', 'Documentaries', 'Culture'], 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Samantha', 'Brown', 'female', 'male', 'straight', 33, 'New York, NY', 'Investment advisor helping clients build wealth. Love financial planning, tennis, and Broadway shows.', ARRAY['Investment Advising', 'Financial Planning', 'Tennis', 'Broadway', 'Wealth Management'], 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Amanda', 'Johnson', 'female', 'male', 'straight', 27, 'Denver, CO', 'Environmental scientist studying climate change. Passionate about research, skiing, and protecting our planet.', ARRAY['Environmental Science', 'Climate Research', 'Skiing', 'Conservation', 'Research'], 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Nicole', 'Martinez', 'female', 'male', 'straight', 29, 'Miami, FL', 'Architect designing sustainable buildings. Love modern design, beach volleyball, and Latin dance.', ARRAY['Architecture', 'Sustainable Design', 'Beach Volleyball', 'Latin Dance', 'Modern Design'], 'https://images.unsplash.com/photo-1494790108755-2616c2b10db8?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Stephanie', 'Garcia', 'female', 'male', 'straight', 31, 'Phoenix, AZ', 'Veterinarian caring for animals. Passionate about animal welfare, desert hiking, and rescue work.', ARRAY['Veterinary Medicine', 'Animal Welfare', 'Desert Hiking', 'Animal Rescue', 'Healthcare'], 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Michelle', 'Lee', 'female', 'male', 'straight', 26, 'Portland, OR', 'UX Designer creating user-friendly experiences. Love design thinking, coffee culture, and weekend markets.', ARRAY['UX Design', 'Design Thinking', 'Coffee Culture', 'Markets', 'User Experience'], 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Kimberly', 'Anderson', 'female', 'male', 'straight', 32, 'Washington, DC', 'Policy analyst working on healthcare reform. Enjoy political discussions, museums, and international cuisine.', ARRAY['Policy Analysis', 'Healthcare Reform', 'Politics', 'Museums', 'International Cuisine'], 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Lisa', 'Thomas', 'female', 'male', 'straight', 28, 'San Diego, CA', 'Marine biologist studying ocean conservation. Love scuba diving, beach running, and marine photography.', ARRAY['Marine Biology', 'Scuba Diving', 'Beach Running', 'Marine Photography', 'Ocean Conservation'], 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Karen', 'Taylor', 'female', 'male', 'straight', 35, 'Atlanta, GA', 'Pharmaceutical researcher developing new treatments. Passionate about medical innovation and improving lives.', ARRAY['Pharmaceutical Research', 'Medical Innovation', 'Healthcare', 'Research', 'Science'], 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Jennifer', 'White', 'female', 'male', 'straight', 30, 'Nashville, TN', 'Music therapist helping people heal through music. Love live music, guitar playing, and therapeutic arts.', ARRAY['Music Therapy', 'Live Music', 'Guitar', 'Therapeutic Arts', 'Healing'], 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Angela', 'Harris', 'female', 'male', 'straight', 29, 'Minneapolis, MN', 'Data analyst turning numbers into insights. Passionate about analytics, winter sports, and problem solving.', ARRAY['Data Analysis', 'Analytics', 'Winter Sports', 'Problem Solving', 'Statistics'], 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Rebecca', 'Clark', 'female', 'male', 'straight', 27, 'Salt Lake City, UT', 'Physical therapist helping athletes recover. Love mountain hiking, CrossFit, and sports medicine.', ARRAY['Physical Therapy', 'Mountain Hiking', 'CrossFit', 'Sports Medicine', 'Athletics'], 'https://images.unsplash.com/photo-1494790108755-2616c2b10db8?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Amy', 'Lewis', 'female', 'male', 'straight', 31, 'Philadelphia, PA', 'Emergency room nurse saving lives daily. Passionate about healthcare, marathon running, and helping others.', ARRAY['Emergency Nursing', 'Healthcare', 'Marathon Running', 'Helping Others', 'Medical Care'], 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Melissa', 'Robinson', 'female', 'male', 'straight', 33, 'Charlotte, NC', 'Financial planner helping families secure their future. Love investment strategy, golf, and family values.', ARRAY['Financial Planning', 'Investment Strategy', 'Golf', 'Family Values', 'Financial Security'], 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Donna', 'Walker', 'female', 'male', 'straight', 26, 'Richmond, VA', 'Cybersecurity specialist protecting digital assets. Passionate about technology security, chess, and problem solving.', ARRAY['Cybersecurity', 'Technology Security', 'Chess', 'Problem Solving', 'Digital Protection'], 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Carol', 'Hall', 'female', 'male', 'straight', 28, 'Indianapolis, IN', 'Manufacturing engineer optimizing production systems. Love efficiency improvement, motorsports, and innovation.', ARRAY['Manufacturing Engineering', 'Efficiency Improvement', 'Motorsports', 'Innovation', 'Production Systems'], 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Sharon', 'Allen', 'female', 'male', 'straight', 30, 'Columbus, OH', 'Digital marketing strategist growing online brands. Passionate about social media, content creation, and brand building.', ARRAY['Digital Marketing', 'Social Media', 'Content Creation', 'Brand Building', 'Online Strategy'], 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Cynthia', 'Young', 'female', 'male', 'straight', 32, 'Jacksonville, FL', 'Aerospace engineer working on next-generation aircraft. Love aviation technology, flying, and space exploration.', ARRAY['Aerospace Engineering', 'Aviation Technology', 'Flying', 'Space Exploration', 'Engineering'], 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Sandra', 'Hernandez', 'female', 'male', 'straight', 29, 'Memphis, TN', 'Chef specializing in fusion cuisine. Passionate about culinary innovation, farm-to-table dining, and food culture.', ARRAY['Culinary Arts', 'Fusion Cuisine', 'Farm-to-Table', 'Food Culture', 'Cooking Innovation'], 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Helen', 'King', 'female', 'male', 'straight', 34, 'Louisville, KY', 'Sports journalist covering professional athletics. Love storytelling, basketball coverage, and behind-the-scenes access.', ARRAY['Sports Journalism', 'Storytelling', 'Basketball', 'Sports Coverage', 'Writing'], 'https://images.unsplash.com/photo-1494790108755-2616c2b10db8?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Linda', 'Wright', 'female', 'male', 'straight', 27, 'Oklahoma City, OK', 'Energy engineer optimizing renewable systems. Passionate about clean energy, outdoor adventures, and sustainability.', ARRAY['Energy Engineering', 'Renewable Energy', 'Outdoor Adventures', 'Sustainability', 'Clean Technology'], 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Patricia', 'Lopez', 'female', 'male', 'straight', 31, 'Las Vegas, NV', 'Hospitality director at luxury resorts. Love creating exceptional experiences, travel, and event coordination.', ARRAY['Hospitality Management', 'Luxury Services', 'Travel', 'Event Coordination', 'Customer Experience'], 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Barbara', 'Hill', 'female', 'male', 'straight', 28, 'Baltimore, MD', 'Biotech researcher developing breakthrough treatments. Passionate about scientific discovery and improving human health.', ARRAY['Biotech Research', 'Scientific Discovery', 'Medical Innovation', 'Health Improvement', 'Laboratory Work'], 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Nancy', 'Scott', 'female', 'male', 'straight', 30, 'Birmingham, AL', 'Civil engineer building sustainable infrastructure. Love construction projects, community development, and green building.', ARRAY['Civil Engineering', 'Sustainable Infrastructure', 'Construction', 'Community Development', 'Green Building'], 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Dorothy', 'Green', 'female', 'male', 'straight', 29, 'Buffalo, NY', 'Mechanical engineer designing automated systems. Passionate about robotics, 3D printing, and engineering solutions.', ARRAY['Mechanical Engineering', 'Robotics', '3D Printing', 'Automated Systems', 'Engineering Solutions'], 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Lisa', 'Adams', 'female', 'male', 'straight', 26, 'New Orleans, LA', 'Jazz vocalist and music teacher sharing the art of music. Love jazz history, live performance, and musical education.', ARRAY['Jazz Music', 'Vocal Performance', 'Music Education', 'Live Performance', 'Jazz History'], 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Betty', 'Baker', 'female', 'male', 'straight', 33, 'Tucson, AZ', 'Desert ecologist studying climate adaptation. Passionate about nature photography, desert conservation, and research.', ARRAY['Desert Ecology', 'Nature Photography', 'Climate Adaptation', 'Desert Conservation', 'Environmental Research'], 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Helen', 'Gonzalez', 'female', 'male', 'straight', 32, 'Albuquerque, NM', 'Solar energy consultant helping businesses transition to renewable power. Love solar technology and sustainable solutions.', ARRAY['Solar Energy', 'Renewable Power', 'Solar Technology', 'Sustainable Solutions', 'Green Consulting'], 'https://images.unsplash.com/photo-1494790108755-2616c2b10db8?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Sandra', 'Nelson', 'female', 'male', 'straight', 28, 'Spokane, WA', 'Park ranger protecting natural resources. Passionate about wilderness conservation, outdoor education, and wildlife protection.', ARRAY['Park Management', 'Wilderness Conservation', 'Outdoor Education', 'Wildlife Protection', 'Natural Resources'], 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Donna', 'Carter', 'female', 'male', 'straight', 31, 'Boise, ID', 'Agricultural engineer improving farming sustainability. Love sustainable agriculture, farm technology, and rural communities.', ARRAY['Agricultural Engineering', 'Sustainable Agriculture', 'Farm Technology', 'Rural Communities', 'Food Systems'], 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Carol', 'Mitchell', 'female', 'male', 'straight', 27, 'Madison, WI', 'Food scientist developing healthy products. Passionate about nutrition research, food safety, and healthy eating.', ARRAY['Food Science', 'Nutrition Research', 'Food Safety', 'Healthy Eating', 'Product Development'], 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Ruth', 'Perez', 'female', 'male', 'straight', 30, 'Des Moines, IA', 'Insurance specialist helping families protect their assets. Love risk assessment, family planning, and financial security.', ARRAY['Insurance Specialist', 'Risk Assessment', 'Family Planning', 'Financial Security', 'Asset Protection'], 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Sharon', 'Roberts', 'female', 'male', 'straight', 29, 'Little Rock, AR', 'Agricultural researcher developing sustainable crops. Passionate about plant science, greenhouse research, and food security.', ARRAY['Agricultural Research', 'Plant Science', 'Greenhouse Research', 'Food Security', 'Sustainable Crops'], 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Laura', 'Turner', 'female', 'male', 'straight', 34, 'Fargo, ND', 'Wind energy engineer developing clean power solutions. Love renewable energy technology and environmental sustainability.', ARRAY['Wind Energy', 'Clean Power', 'Renewable Energy Technology', 'Environmental Sustainability', 'Green Engineering'], 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Cynthia', 'Phillips', 'female', 'male', 'straight', 26, 'Burlington, VT', 'Organic farmer growing sustainable produce. Passionate about organic farming, farmers markets, and local food systems.', ARRAY['Organic Farming', 'Sustainable Agriculture', 'Farmers Markets', 'Local Food Systems', 'Sustainable Living'], 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=600&fit=crop', true),

-- Lesbian Females (5)
(gen_random_uuid(), 'Riley', 'Thompson', 'female', 'female', 'gay', 29, 'Portland, OR', 'Environmental scientist and rock climber. Love exploring national parks, sustainable living, and cozy coffee shop dates.', ARRAY['Environmental Science', 'Rock Climbing', 'National Parks', 'Sustainable Living', 'Coffee'], 'https://images.unsplash.com/photo-1494790108755-2616c2b10db8?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Taylor', 'Brooks', 'female', 'female', 'gay', 27, 'San Francisco, CA', 'Software engineer and indie musician. Write songs about love and life, looking for someone to harmonize with.', ARRAY['Software Engineering', 'Indie Music', 'Songwriting', 'Live Music', 'Technology'], 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Morgan', 'Davis', 'female', 'female', 'gay', 31, 'Brooklyn, NY', 'Documentary filmmaker telling important stories. Passionate about social justice, LGBTQ+ rights, and visual storytelling.', ARRAY['Documentary Filmmaking', 'Social Justice', 'LGBTQ+ Rights', 'Visual Storytelling', 'Human Rights'], 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Jamie', 'Wilson', 'female', 'female', 'gay', 28, 'Austin, TX', 'Veterinarian specializing in wildlife rehabilitation. Love animal conservation, hiking, and outdoor adventures.', ARRAY['Veterinary Medicine', 'Wildlife Rehabilitation', 'Animal Conservation', 'Hiking', 'Outdoor Adventures'], 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Casey', 'Martinez', 'female', 'female', 'gay', 30, 'Seattle, WA', 'Chef and restaurant owner creating farm-to-table experiences. Passionate about culinary arts and local ingredients.', ARRAY['Culinary Arts', 'Restaurant Management', 'Farm-to-Table', 'Local Ingredients', 'Food Innovation'], 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=600&fit=crop', true),

-- Bisexual Females (5)
(gen_random_uuid(), 'Alex', 'Morgan', 'female', 'any', 'bisexual', 26, 'Austin, TX', 'Freelance graphic designer with a love for live music. Believe love has no boundaries and seeking authentic connections.', ARRAY['Graphic Design', 'Live Music', 'Food Trucks', 'Art', 'Creative Writing'], 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Sam', 'Taylor', 'female', 'any', 'bisexual', 29, 'Denver, CO', 'Environmental consultant working on sustainability projects. Open to connections based on personality and shared values.', ARRAY['Environmental Consulting', 'Sustainability', 'Outdoor Recreation', 'Conservation', 'Green Living'], 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Drew', 'Anderson', 'female', 'any', 'bisexual', 32, 'Chicago, IL', 'Social worker helping families in need. Believe in connecting with people regardless of gender identity.', ARRAY['Social Work', 'Family Support', 'Community Service', 'Mental Health', 'Advocacy'], 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'Phoenix', 'Lee', 'female', 'any', 'bisexual', 27, 'Los Angeles, CA', 'Film editor creating compelling stories. Value authentic connections that transcend traditional boundaries.', ARRAY['Film Editing', 'Storytelling', 'Cinema', 'Creative Arts', 'Visual Media'], 'https://images.unsplash.com/photo-1494790108755-2616c2b10db8?w=400&h=600&fit=crop', true),
(gen_random_uuid(), 'River', 'Johnson', 'female', 'any', 'bisexual', 28, 'Portland, OR', 'Mental health counselor creating safe spaces. Looking for meaningful connections based on emotional intelligence and growth.', ARRAY['Mental Health Counseling', 'Safe Spaces', 'Emotional Intelligence', 'Personal Growth', 'Therapy'], 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=600&fit=crop', true);

-- Add compatibility answers for all profiles
INSERT INTO compatibility_answers (user_id, answers, completed_at, updated_at)
SELECT 
  user_id,
  jsonb_build_object(
    '7', CASE 
      WHEN gender = 'male' THEN 'Male'
      WHEN gender = 'female' THEN 'Female'  
      WHEN gender = 'non-binary' THEN 'Non-binary'
      ELSE 'Male'
    END,
    '12', CASE 
      WHEN seeking_gender = 'female' THEN 'Women'
      WHEN seeking_gender = 'male' THEN 'Men'
      WHEN seeking_gender = 'any' THEN 'Everyone'
      ELSE 'Everyone'
    END,
    'social_energy', (ARRAY['alone', 'social', 'balanced'])[floor(random() * 3 + 1)],
    'decision_making', (ARRAY['logical', 'emotional', 'collaborative'])[floor(random() * 3 + 1)],
    'lifestyle_pace', (ARRAY['adventurous', 'balanced', 'peaceful'])[floor(random() * 3 + 1)],
    'conflict_style', (ARRAY['direct', 'diplomatic', 'space'])[floor(random() * 3 + 1)],
    'future_planning', (ARRAY['planner', 'flexible', 'spontaneous'])[floor(random() * 3 + 1)],
    'love_language', (ARRAY['words', 'time', 'touch', 'acts', 'gifts'])[floor(random() * 5 + 1)]
  ) as answers,
  now() as completed_at,
  now() as updated_at
FROM dating_profiles
WHERE NOT EXISTS (
  SELECT 1 FROM compatibility_answers WHERE compatibility_answers.user_id = dating_profiles.user_id
);