-- Create function to seed dating profiles bypassing RLS
CREATE OR REPLACE FUNCTION seed_dating_profiles()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Delete existing profiles to avoid duplicates
  DELETE FROM dating_profiles;
  
  -- Insert male profiles
  INSERT INTO dating_profiles (first_name, last_name, age, gender, city, state, bio, interests, relationship_goals, partner_preferences, photo_urls, email) VALUES
  ('Alex', 'Rodriguez', 28, 'Male', 'New York', 'NY', 'Software engineer who loves hiking and cooking. Always up for trying new restaurants or exploring hidden gems in the city.', ARRAY['Hiking', 'Cooking', 'Photography', 'Travel', 'Coffee'], 'Long-term relationship', 'Someone who loves adventure and has a great sense of humor', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face'], 'alex.rodriguez.dating@example.com'),
  ('Michael', 'Chen', 32, 'Male', 'San Francisco', 'CA', 'Tech entrepreneur with a passion for sustainable living. Weekends find me at farmers markets or planning my next startup idea.', ARRAY['Sustainability', 'Entrepreneurship', 'Rock Climbing', 'Yoga', 'Wine Tasting'], 'Long-term relationship', 'An independent, eco-conscious woman who shares my values', ARRAY['https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face'], 'michael.chen.dating@example.com'),
  ('David', 'Thompson', 26, 'Male', 'Austin', 'TX', 'Musician by night, marketing manager by day. Love live music, tacos, and long conversations over craft beer.', ARRAY['Music', 'Guitar', 'Live Concerts', 'Craft Beer', 'Food Trucks'], 'Casual dating', 'Someone who appreciates good music and isn''t afraid to dance', ARRAY['https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face'], 'david.thompson.dating@example.com'),
  ('James', 'Wilson', 35, 'Male', 'Chicago', 'IL', 'Financial advisor who values work-life balance. Passionate about fitness, reading, and weekend getaways to Michigan.', ARRAY['Fitness', 'Reading', 'Travel', 'Basketball', 'Investing'], 'Long-term relationship', 'A driven woman who values personal growth and communication', ARRAY['https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400&h=400&fit=crop&crop=face'], 'james.wilson.dating@example.com'),
  ('Ryan', 'Murphy', 29, 'Male', 'Denver', 'CO', 'Outdoor enthusiast and graphic designer. If I''m not skiing in winter, I''m hiking in summer. Love dogs and good design.', ARRAY['Skiing', 'Hiking', 'Design', 'Dogs', 'Photography'], 'Long-term relationship', 'An active, creative soul who loves the outdoors as much as I do', ARRAY['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=face'], 'ryan.murphy.dating@example.com'),
  ('Carlos', 'Santos', 31, 'Male', 'Miami', 'FL', 'Bilingual architect who loves salsa dancing and beach volleyball. Family-oriented and always planning the next adventure.', ARRAY['Salsa Dancing', 'Beach Volleyball', 'Architecture', 'Travel', 'Cooking'], 'Long-term relationship', 'Someone who values family and loves to dance and travel', ARRAY['https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=400&h=400&fit=crop&crop=face'], 'carlos.santos.dating@example.com'),
  ('Brandon', 'Lee', 27, 'Male', 'Seattle', 'WA', 'Coffee roaster and part-time writer. Love exploring new neighborhoods, trying local breweries, and rainy day reading sessions.', ARRAY['Coffee', 'Writing', 'Craft Beer', 'Reading', 'Urban Exploration'], 'Casual dating', 'Someone who appreciates good coffee and meaningful conversations', ARRAY['https://images.unsplash.com/photo-1521119989659-a83eee488004?w=400&h=400&fit=crop&crop=face'], 'brandon.lee.dating@example.com'),
  ('Kevin', 'Johnson', 33, 'Male', 'Boston', 'MA', 'History professor who loves trivia nights and exploring historical sites. Also a weekend warrior on the tennis court.', ARRAY['History', 'Tennis', 'Trivia', 'Museums', 'Travel'], 'Long-term relationship', 'An intelligent, curious woman who enjoys learning new things', ARRAY['https://images.unsplash.com/photo-1502764613149-7f1d229e230f?w=400&h=400&fit=crop&crop=face'], 'kevin.johnson.dating@example.com'),
  ('Marcus', 'Davis', 30, 'Male', 'Atlanta', 'GA', 'Physical therapist with a love for helping others. Enjoy morning runs, cooking healthy meals, and Sunday football.', ARRAY['Running', 'Healthy Cooking', 'Football', 'Fitness', 'Volunteering'], 'Long-term relationship', 'A caring, health-conscious woman who shares my values', ARRAY['https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face'], 'marcus.davis.dating@example.com'),
  ('Daniel', 'Kim', 25, 'Male', 'Los Angeles', 'CA', 'Film student and aspiring director. Love indie movies, street photography, and discovering new bands before they''re cool.', ARRAY['Film', 'Photography', 'Music', 'Art', 'Filmmaking'], 'Casual dating', 'A creative spirit who appreciates art and good cinema', ARRAY['https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&h=400&fit=crop&crop=face'], 'daniel.kim.dating@example.com'),
  ('Noah', 'Anderson', 34, 'Male', 'Portland', 'OR', 'Environmental scientist and weekend farmer. Passionate about sustainability, local food, and building a better future.', ARRAY['Environment', 'Gardening', 'Sustainable Living', 'Hiking', 'Local Food'], 'Long-term relationship', 'Someone who cares about the planet and enjoys simple pleasures', ARRAY['https://images.unsplash.com/photo-1489980557514-251d61e3eeb6?w=400&h=400&fit=crop&crop=face'], 'noah.anderson.dating@example.com'),
  ('Tyler', 'Brown', 28, 'Male', 'Nashville', 'TN', 'Country music producer who loves live shows and discovering new talent. Also enjoy barbecue, bourbon, and good company.', ARRAY['Country Music', 'Live Music', 'Barbecue', 'Bourbon', 'Nashville'], 'Long-term relationship', 'A music lover who appreciates authenticity and good times', ARRAY['https://images.unsplash.com/photo-1507038732509-8b4d5fdfacc6?w=400&h=400&fit=crop&crop=face'], 'tyler.brown.dating@example.com'),
  ('Jacob', 'Martinez', 26, 'Male', 'Phoenix', 'AZ', 'Desert lover and solar energy engineer. Enjoy rock climbing, stargazing, and exploring Arizona''s natural beauty.', ARRAY['Rock Climbing', 'Stargazing', 'Solar Energy', 'Desert Hiking', 'Camping'], 'Casual dating', 'An adventurous woman who loves the outdoors and clear skies', ARRAY['https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?w=400&h=400&fit=crop&crop=face'], 'jacob.martinez.dating@example.com'),
  ('Ethan', 'Taylor', 32, 'Male', 'Philadelphia', 'PA', 'Lawyer with a passion for social justice. Love cheesesteaks, Eagles games, and heated debates about everything.', ARRAY['Social Justice', 'Football', 'Debate', 'Local Food', 'Reading'], 'Long-term relationship', 'An intelligent, passionate woman who stands up for her beliefs', ARRAY['https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face'], 'ethan.taylor.dating@example.com'),
  ('Luke', 'Garcia', 29, 'Male', 'San Diego', 'CA', 'Marine biologist who spends days studying ocean life. Love surfing, beach volleyball, and fish tacos by the pier.', ARRAY['Marine Biology', 'Surfing', 'Beach Volleyball', 'Ocean Conservation', 'Tacos'], 'Long-term relationship', 'Someone who loves the ocean and cares about marine conservation', ARRAY['https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=400&h=400&fit=crop&crop=face'], 'luke.garcia.dating@example.com'),
  ('Andrew', 'White', 31, 'Male', 'Washington', 'DC', 'Policy analyst who believes in making a difference. Enjoy museums, political discussions, and weekend trips to Virginia wine country.', ARRAY['Politics', 'Museums', 'Wine Tasting', 'Policy', 'Current Events'], 'Long-term relationship', 'An educated, socially aware woman who enjoys deep conversations', ARRAY['https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face'], 'andrew.white.dating@example.com'),
  ('Connor', 'Moore', 27, 'Male', 'Detroit', 'MI', 'Automotive engineer with a love for classic cars. Enjoy hockey games, craft beer, and rebuilding vintage engines.', ARRAY['Classic Cars', 'Hockey', 'Craft Beer', 'Engineering', 'Vintage Restoration'], 'Casual dating', 'Someone who appreciates craftsmanship and isn''t afraid to get their hands dirty', ARRAY['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=face'], 'connor.moore.dating@example.com'),
  ('Ian', 'Clark', 30, 'Male', 'Minneapolis', 'MN', 'Data scientist who loves solving puzzles. Enjoy winter sports, board games, and finding the best coffee shops in the Twin Cities.', ARRAY['Data Science', 'Winter Sports', 'Board Games', 'Coffee', 'Puzzles'], 'Long-term relationship', 'A smart, analytical woman who enjoys intellectual challenges', ARRAY['https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400&h=400&fit=crop&crop=face'], 'ian.clark.dating@example.com'),
  ('Jordan', 'Lewis', 26, 'Male', 'Salt Lake City', 'UT', 'Adventure guide who lives for the mountains. Love skiing, mountain biking, and sharing Utah''s incredible outdoor playground.', ARRAY['Skiing', 'Mountain Biking', 'Adventure Tourism', 'Outdoor Photography', 'Camping'], 'Long-term relationship', 'An adventure-loving woman who enjoys mountain life', ARRAY['https://images.unsplash.com/photo-1507591064344-4c6ce005b128?w=400&h=400&fit=crop&crop=face'], 'jordan.lewis.dating@example.com'),
  ('Mason', 'Walker', 33, 'Male', 'Las Vegas', 'NV', 'Event coordinator who knows how to have a good time. Love live entertainment, trying new restaurants, and weekend desert adventures.', ARRAY['Event Planning', 'Live Entertainment', 'Desert Adventures', 'Fine Dining', 'Travel'], 'Casual dating', 'Someone who enjoys the excitement of city life and good entertainment', ARRAY['https://images.unsplash.com/photo-1521119989659-a83eee488004?w=400&h=400&fit=crop&crop=face'], 'mason.walker.dating@example.com'),
  ('Logan', 'Hall', 28, 'Male', 'New Orleans', 'LA', 'Jazz musician and music teacher. Love the culture, food, and music of NOLA. Always ready for a good festival or street performance.', ARRAY['Jazz Music', 'Teaching', 'New Orleans Culture', 'Festivals', 'Creole Cuisine'], 'Long-term relationship', 'A music lover who appreciates culture and good food', ARRAY['https://images.unsplash.com/photo-1502764613149-7f1d229e230f?w=400&h=400&fit=crop&crop=face'], 'logan.hall.dating@example.com'),
  ('Blake', 'Allen', 25, 'Male', 'Charlotte', 'NC', 'Banking professional with Southern charm. Love NASCAR, barbecue, and weekend trips to the Blue Ridge Mountains.', ARRAY['NASCAR', 'Barbecue', 'Mountain Hiking', 'Banking', 'Southern Culture'], 'Long-term relationship', 'A sweet, genuine woman who appreciates Southern hospitality', ARRAY['https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=400&h=400&fit=crop&crop=face'], 'blake.allen.dating@example.com'),
  ('Hunter', 'Young', 31, 'Male', 'Kansas City', 'MO', 'Barbecue pitmaster and food blogger. Passionate about authentic flavors, Chiefs football, and sharing great meals with great people.', ARRAY['Barbecue', 'Food Blogging', 'Football', 'Cooking', 'Local Food Scene'], 'Long-term relationship', 'A foodie who appreciates good barbecue and football Sundays', ARRAY['https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&h=400&fit=crop&crop=face'], 'hunter.young.dating@example.com'),
  ('Cole', 'King', 29, 'Male', 'Tampa', 'FL', 'Marine veteran turned personal trainer. Love fitness challenges, beach workouts, and helping others reach their goals.', ARRAY['Fitness', 'Military', 'Beach Sports', 'Personal Training', 'Goal Setting'], 'Long-term relationship', 'A strong, motivated woman who values fitness and personal growth', ARRAY['https://images.unsplash.com/photo-1489980557514-251d61e3eeb6?w=400&h=400&fit=crop&crop=face'], 'cole.king.dating@example.com'),
  ('Cameron', 'Wright', 32, 'Male', 'Sacramento', 'CA', 'Government employee who loves public service. Enjoy river rafting, wine country trips, and exploring California''s diverse landscapes.', ARRAY['Public Service', 'River Rafting', 'Wine Tasting', 'California Nature', 'Civic Engagement'], 'Long-term relationship', 'Someone who values community service and California living', ARRAY['https://images.unsplash.com/photo-1507038732509-8b4d5fdfacc6?w=400&h=400&fit=crop&crop=face'], 'cameron.wright.dating@example.com');

  -- Insert female profiles  
  INSERT INTO dating_profiles (first_name, last_name, age, gender, city, state, bio, interests, relationship_goals, partner_preferences, photo_urls, email) VALUES
  ('Emma', 'Johnson', 27, 'Female', 'New York', 'NY', 'Marketing creative who loves brunch, Broadway shows, and weekend escapes to the Hamptons. Always planning the next adventure.', ARRAY['Theater', 'Brunch', 'Marketing', 'Travel', 'Art'], 'Long-term relationship', 'An ambitious guy who can keep up with city life and loves culture', ARRAY['https://images.unsplash.com/photo-1494790108755-2616b612b182?w=400&h=400&fit=crop&crop=face'], 'emma.johnson.dating@example.com'),
  ('Sophia', 'Davis', 25, 'Female', 'Los Angeles', 'CA', 'Yoga instructor and wellness blogger. Love sunrise hikes, green smoothies, and spreading positive vibes wherever I go.', ARRAY['Yoga', 'Wellness', 'Hiking', 'Healthy Living', 'Meditation'], 'Long-term relationship', 'A mindful, health-conscious man who values personal growth', ARRAY['https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face'], 'sophia.davis.dating@example.com'),
  ('Olivia', 'Miller', 29, 'Female', 'Chicago', 'IL', 'Nurse with a big heart for helping others. Love deep dish pizza, Cubs games, and cozy nights watching Netflix.', ARRAY['Healthcare', 'Baseball', 'Netflix', 'Deep Dish Pizza', 'Volunteering'], 'Long-term relationship', 'A kind, genuine man who values compassion and loyalty', ARRAY['https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400&h=400&fit=crop&crop=face'], 'olivia.miller.dating@example.com'),
  ('Isabella', 'Garcia', 31, 'Female', 'Miami', 'FL', 'Fashion designer with Latin roots. Love salsa dancing, art deco architecture, and creating beautiful things that make people feel confident.', ARRAY['Fashion Design', 'Salsa Dancing', 'Art', 'Latin Culture', 'Architecture'], 'Long-term relationship', 'A passionate man who appreciates art, culture, and family values', ARRAY['https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&crop=face'], 'isabella.garcia.dating@example.com'),
  ('Ava', 'Brown', 26, 'Female', 'Austin', 'TX', 'Food blogger who eats her way through Austin''s amazing food scene. Love live music, food trucks, and discovering hidden gems.', ARRAY['Food Blogging', 'Live Music', 'Food Trucks', 'Austin Culture', 'Photography'], 'Casual dating', 'A foodie musician who knows the best taco spots in town', ARRAY['https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop&crop=face'], 'ava.brown.dating@example.com'),
  ('Mia', 'Wilson', 28, 'Female', 'Seattle', 'WA', 'Environmental lawyer fighting for our planet. Love hiking in the Cascades, indie coffee shops, and rainy day book marathons.', ARRAY['Environmental Law', 'Hiking', 'Coffee', 'Reading', 'Sustainability'], 'Long-term relationship', 'An environmentally conscious man who loves the Pacific Northwest', ARRAY['https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=400&fit=crop&crop=face'], 'mia.wilson.dating@example.com'),
  ('Charlotte', 'Moore', 30, 'Female', 'Boston', 'MA', 'History PhD student who loves uncovering stories from the past. Enjoy museum visits, bookstore browsing, and Freedom Trail walks.', ARRAY['History', 'Museums', 'Books', 'Academic Research', 'Boston'], 'Long-term relationship', 'An intelligent, curious man who enjoys learning and deep conversations', ARRAY['https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop&crop=face'], 'charlotte.moore.dating@example.com'),
  ('Amelia', 'Taylor', 24, 'Female', 'Denver', 'CO', 'Adventure photographer capturing Colorado''s beauty. Love skiing, mountain biking, and chasing golden hour light in the Rockies.', ARRAY['Photography', 'Skiing', 'Mountain Biking', 'Adventure', 'Nature'], 'Casual dating', 'An outdoor enthusiast who loves adventure and beautiful landscapes', ARRAY['https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face'], 'amelia.taylor.dating@example.com'),
  ('Harper', 'Anderson', 32, 'Female', 'San Francisco', 'CA', 'Tech startup founder building the future. Love innovation, weekend wine country trips, and finding the best dim sum in Chinatown.', ARRAY['Technology', 'Entrepreneurship', 'Wine', 'Innovation', 'Dim Sum'], 'Long-term relationship', 'An ambitious, forward-thinking man who shares my entrepreneurial spirit', ARRAY['https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face'], 'harper.anderson.dating@example.com'),
  ('Evelyn', 'Thomas', 27, 'Female', 'Nashville', 'TN', 'Country music songwriter with a voice and stories to tell. Love honky-tonk bars, songwriting sessions, and authentic Southern cuisine.', ARRAY['Country Music', 'Songwriting', 'Nashville', 'Southern Culture', 'Storytelling'], 'Long-term relationship', 'A music lover who appreciates authenticity and good storytelling', ARRAY['https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=400&fit=crop&crop=face'], 'evelyn.thomas.dating@example.com'),
  ('Abigail', 'Jackson', 29, 'Female', 'Portland', 'OR', 'Craft beer sommelier and local food advocate. Love brewery tours, farmers markets, and keeping Portland weird.', ARRAY['Craft Beer', 'Local Food', 'Farmers Markets', 'Portland Culture', 'Sustainability'], 'Long-term relationship', 'A local food enthusiast who appreciates Portland''s unique culture', ARRAY['https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=400&h=400&fit=crop&crop=face'], 'abigail.jackson.dating@example.com'),
  ('Emily', 'White', 26, 'Female', 'Atlanta', 'GA', 'Event planner who loves bringing people together. Enjoy Southern hospitality, peach everything, and planning unforgettable experiences.', ARRAY['Event Planning', 'Southern Culture', 'Hospitality', 'Peach Cobbler', 'Celebrations'], 'Long-term relationship', 'A social, family-oriented man who appreciates Southern charm', ARRAY['https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=400&fit=crop&crop=face'], 'emily.white.dating@example.com'),
  ('Madison', 'Harris', 25, 'Female', 'San Diego', 'CA', 'Marine biology graduate student studying ocean conservation. Love surfing at dawn, fish tacos, and protecting our blue planet.', ARRAY['Marine Biology', 'Surfing', 'Ocean Conservation', 'Research', 'Beach Life'], 'Long-term relationship', 'An ocean lover who cares about marine conservation', ARRAY['https://images.unsplash.com/photo-1494790108755-2616b612b182?w=400&h=400&fit=crop&crop=face'], 'madison.harris.dating@example.com'),
  ('Elizabeth', 'Martin', 33, 'Female', 'Washington', 'DC', 'Political journalist covering Capitol Hill. Love press briefings, museum galas, and weekend escapes to Virginia wine country.', ARRAY['Journalism', 'Politics', 'Museums', 'Wine', 'Current Events'], 'Long-term relationship', 'An intelligent, well-informed man who enjoys political discussions', ARRAY['https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face'], 'elizabeth.martin.dating@example.com'),
  ('Victoria', 'Thompson', 28, 'Female', 'Philadelphia', 'PA', 'Art curator with a passion for contemporary works. Love gallery openings, cheesesteaks, and discovering emerging artists.', ARRAY['Art Curation', 'Contemporary Art', 'Gallery Events', 'Philadelphia', 'Emerging Artists'], 'Long-term relationship', 'A cultured man who appreciates art and Philadelphia''s rich history', ARRAY['https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400&h=400&fit=crop&crop=face'], 'victoria.thompson.dating@example.com'),
  ('Grace', 'Lee', 30, 'Female', 'Phoenix', 'AZ', 'Desert landscape architect creating sustainable outdoor spaces. Love hiking Camelback, desert sunsets, and innovative design.', ARRAY['Landscape Architecture', 'Desert Hiking', 'Sustainable Design', 'Sunsets', 'Innovation'], 'Long-term relationship', 'An environmentally conscious man who loves desert landscapes', ARRAY['https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&crop=face'], 'grace.lee.dating@example.com'),
  ('Chloe', 'Clark', 24, 'Female', 'Minneapolis', 'MN', 'Social media manager who loves connecting people online and offline. Enjoy winter festivals, lake summers, and Minnesota nice vibes.', ARRAY['Social Media', 'Winter Sports', 'Lake Activities', 'Festivals', 'Community Building'], 'Casual dating', 'A social, winter-loving guy who enjoys Minnesota''s unique culture', ARRAY['https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop&crop=face'], 'chloe.clark.dating@example.com'),
  ('Scarlett', 'Lewis', 31, 'Female', 'Las Vegas', 'NV', 'Casino marketing manager who knows Vegas inside and out. Love high-energy entertainment, fine dining, and desert adventures.', ARRAY['Entertainment Marketing', 'Fine Dining', 'Desert Adventures', 'Las Vegas', 'Live Shows'], 'Casual dating', 'An exciting man who enjoys the Vegas lifestyle and good entertainment', ARRAY['https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=400&h=400&fit=crop&crop=face'], 'scarlett.lewis.dating@example.com'),
  ('Zoey', 'Walker', 27, 'Female', 'Salt Lake City', 'UT', 'Outdoor gear designer creating products for mountain adventures. Love backcountry skiing, rock climbing, and Utah''s incredible landscapes.', ARRAY['Outdoor Gear Design', 'Backcountry Skiing', 'Rock Climbing', 'Mountain Adventures', 'Product Design'], 'Long-term relationship', 'An adventurous man who loves mountain sports and outdoor gear', ARRAY['https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop&crop=face'], 'zoey.walker.dating@example.com'),
  ('Luna', 'Hall', 26, 'Female', 'New Orleans', 'LA', 'Jazz vocalist keeping NOLA music traditions alive. Love street performances, beignets, and the magic of French Quarter nights.', ARRAY['Jazz Music', 'Vocals', 'New Orleans Culture', 'Street Performance', 'French Quarter'], 'Long-term relationship', 'A music lover who appreciates NOLA culture and live performance', ARRAY['https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop&crop=face'], 'luna.hall.dating@example.com'),
  ('Stella', 'Allen', 29, 'Female', 'Charlotte', 'NC', 'Southern belle working in finance with modern values. Love NASCAR weekends, mountain getaways, and balancing tradition with progress.', ARRAY['Finance', 'NASCAR', 'Mountain Trips', 'Southern Traditions', 'Modern Values'], 'Long-term relationship', 'A gentleman who respects Southern values but embraces modern thinking', ARRAY['https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face'], 'stella.allen.dating@example.com'),
  ('Hazel', 'Young', 25, 'Female', 'Kansas City', 'MO', 'BBQ competition judge with a refined palate. Love Chiefs football, local breweries, and finding the perfect burnt ends.', ARRAY['BBQ Judging', 'Football', 'Local Breweries', 'Food Competitions', 'Kansas City'], 'Long-term relationship', 'A BBQ lover who appreciates good food and football Sundays', ARRAY['https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&h=400&fit=crop&crop=face'], 'hazel.young.dating@example.com'),
  ('Aurora', 'King', 32, 'Female', 'Tampa', 'FL', 'Fitness influencer promoting healthy lifestyles. Love beach workouts, smoothie bowls, and inspiring others to reach their potential.', ARRAY['Fitness Influencing', 'Beach Workouts', 'Healthy Eating', 'Motivation', 'Social Media'], 'Long-term relationship', 'A fit, motivated man who values health and personal development', ARRAY['https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=400&h=400&fit=crop&crop=face'], 'aurora.king.dating@example.com'),
  ('Savannah', 'Wright', 28, 'Female', 'Sacramento', 'CA', 'Government policy analyst working on California''s future. Love wine country weekends, river rafting, and making positive change.', ARRAY['Policy Analysis', 'Wine Country', 'River Rafting', 'California Politics', 'Public Service'], 'Long-term relationship', 'A socially conscious man who cares about California''s future', ARRAY['https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=400&fit=crop&crop=face'], 'savannah.wright.dating@example.com'),
  ('Brooklyn', 'Scott', 30, 'Female', 'Detroit', 'MI', 'Urban revitalization specialist helping rebuild Motor City. Love Red Wings hockey, craft cocktails, and Detroit''s comeback story.', ARRAY['Urban Planning', 'Hockey', 'Craft Cocktails', 'Detroit History', 'Community Development'], 'Long-term relationship', 'A man who believes in Detroit''s potential and loves hockey', ARRAY['https://images.unsplash.com/photo-1494790108755-2616b612b182?w=400&h=400&fit=crop&crop=face'], 'brooklyn.scott.dating@example.com');

  RAISE NOTICE 'Successfully seeded 50 dating profiles!';
END;
$$;

-- Execute the seeding function
SELECT seed_dating_profiles();