#!/usr/bin/env node
/**
 * BUILD-TIME ENVIRONMENT VARIABLE INJECTION
 *
 * This script runs during Vercel build to inject environment variables
 * directly into env-config.js. Values are JSON.stringify'd to handle
 * special characters safely.
 */

const fs = require('fs');
const path = require('path');

// Helper to clean env vars (remove whitespace, newlines)
const clean = (val) => (val || '').replace(/[\s\n\r]+/g, '').trim();

// Read environment variables (set in Vercel dashboard)
const config = {
    SUPABASE_URL: clean(process.env.SUPABASE_URL),
    SUPABASE_ANON_KEY: clean(process.env.SUPABASE_ANON_KEY),
    STRIPE_PUBLIC_KEY: clean(process.env.STRIPE_PUBLIC_KEY),
    STRIPE_LINK_BASIC: clean(process.env.STRIPE_LINK_BASIC),
    STRIPE_LINK_ADVANCED: clean(process.env.STRIPE_LINK_ADVANCED),
    STRIPE_LINK_PREMIUM: clean(process.env.STRIPE_LINK_PREMIUM),
    STRIPE_PRICE_INSTANT: clean(process.env.STRIPE_PRICE_INSTANT),
    STRIPE_PRICE_PRECISION: clean(process.env.STRIPE_PRICE_PRECISION),
    STRIPE_PRICE_LEGENDARY: clean(process.env.STRIPE_PRICE_LEGENDARY)
};

console.log('');
console.log('═══════════════════════════════════════════════════════════════');
console.log('📦 BUILD-ENV.JS - Building env-config.js');
console.log('═══════════════════════════════════════════════════════════════');
console.log('Build time:', new Date().toISOString());
console.log('Node version:', process.version);
console.log('Working directory:', __dirname);
console.log('');
console.log('RAW environment variables:');
console.log('   process.env.SUPABASE_URL =', JSON.stringify(process.env.SUPABASE_URL));
console.log('   process.env.SUPABASE_ANON_KEY =', process.env.SUPABASE_ANON_KEY ? '[SET - ' + process.env.SUPABASE_ANON_KEY.length + ' chars]' : '[NOT SET]');
console.log('');
console.log('After clean():');
console.log('   SUPABASE_URL:', config.SUPABASE_URL ? '✓ "' + config.SUPABASE_URL + '"' : '✗ EMPTY');
console.log('   SUPABASE_ANON_KEY:', config.SUPABASE_ANON_KEY ? '✓ Set (length: ' + config.SUPABASE_ANON_KEY.length + ')' : '✗ EMPTY');
console.log('   STRIPE_PUBLIC_KEY:', config.STRIPE_PUBLIC_KEY ? '✓ Set' : '✗ Empty');
console.log('');
console.log('All env vars containing SUPA:', Object.keys(process.env).filter(k => k.includes('SUPA')).join(', ') || 'NONE');
console.log('All env vars containing STRIPE:', Object.keys(process.env).filter(k => k.includes('STRIPE')).join(', ') || 'NONE');
console.log('');

// Generate env-config.js with values injected at build time
// Using JSON.stringify ensures special characters are properly escaped
const configContent = `// Environment configuration for LuvLang Mastering
// AUTO-GENERATED by build-env.js at build time
// Build: ${new Date().toISOString()}
// DO NOT EDIT - changes will be overwritten on next deploy

console.log('📦 env-config.js loaded (build-time injected)');

window.__ENV__ = {
    SUPABASE_URL: ${JSON.stringify(config.SUPABASE_URL)},
    SUPABASE_ANON_KEY: ${JSON.stringify(config.SUPABASE_ANON_KEY)},
    STRIPE_PUBLIC_KEY: ${JSON.stringify(config.STRIPE_PUBLIC_KEY)},
    STRIPE_LINK_BASIC: ${JSON.stringify(config.STRIPE_LINK_BASIC)},
    STRIPE_LINK_ADVANCED: ${JSON.stringify(config.STRIPE_LINK_ADVANCED)},
    STRIPE_LINK_PREMIUM: ${JSON.stringify(config.STRIPE_LINK_PREMIUM)},
    STRIPE_PRICE_INSTANT: ${JSON.stringify(config.STRIPE_PRICE_INSTANT)},
    STRIPE_PRICE_PRECISION: ${JSON.stringify(config.STRIPE_PRICE_PRECISION)},
    STRIPE_PRICE_LEGENDARY: ${JSON.stringify(config.STRIPE_PRICE_LEGENDARY)},
    _loaded: true,
    _error: null
};

console.log('✅ Environment config ready');
console.log('   SUPABASE_URL:', window.__ENV__.SUPABASE_URL ? '✓ Set' : '✗ Missing');
console.log('   SUPABASE_ANON_KEY:', window.__ENV__.SUPABASE_ANON_KEY ? '✓ Set' : '✗ Missing');

// Dispatch event so other scripts know config is ready
window.dispatchEvent(new CustomEvent('envConfigLoaded', { detail: window.__ENV__ }));
`;

// Write to env-config.js
const outputPath = path.join(__dirname, 'env-config.js');
fs.writeFileSync(outputPath, configContent);

console.log('✅ env-config.js generated with build-time values');

// Validate
if (!config.SUPABASE_URL || !config.SUPABASE_ANON_KEY) {
    console.warn('⚠️  Warning: Missing Supabase credentials');
    console.warn('   Set SUPABASE_URL and SUPABASE_ANON_KEY in Vercel Environment Variables');
}
