#!/usr/bin/env node
/**
 * BUILD-TIME ENVIRONMENT VARIABLE INJECTION
 *
 * This script runs during Vercel build to generate env-config.js
 * The generated file fetches config from /api/config endpoint at runtime
 */

const fs = require('fs');
const path = require('path');

// Check if environment variables are set (for logging only)
const config = {
    SUPABASE_URL: process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL || '',
    SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_ANON_KEY || '',
    STRIPE_PUBLIC_KEY: process.env.STRIPE_PUBLIC_KEY || process.env.VITE_STRIPE_PUBLIC_KEY || '',
};

console.log('📦 Building env-config.js...');
console.log('   SUPABASE_URL:', config.SUPABASE_URL ? '✓ Set in environment' : '✗ Not set (will use API)');
console.log('   SUPABASE_ANON_KEY:', config.SUPABASE_ANON_KEY ? '✓ Set in environment' : '✗ Not set (will use API)');
console.log('   STRIPE_PUBLIC_KEY:', config.STRIPE_PUBLIC_KEY ? '✓ Set in environment' : '✗ Not set (will use API)');

// Generate env-config.js that fetches from API at runtime
// This is more reliable than build-time injection
const configContent = `// Environment configuration for LuvLang Mastering
// AUTO-GENERATED by build-env.js - Fetches config from /api/config
// Build time: ${new Date().toISOString()}

console.log('📦 env-config.js loaded');

// Initialize global config object
(function() {
    try {
        window.__ENV__ = {
            SUPABASE_URL: '',
            SUPABASE_ANON_KEY: '',
            STRIPE_PUBLIC_KEY: '',
            STRIPE_LINK_BASIC: '',
            STRIPE_LINK_ADVANCED: '',
            STRIPE_LINK_PREMIUM: '',
            STRIPE_PRICE_INSTANT: '',
            STRIPE_PRICE_PRECISION: '',
            STRIPE_PRICE_LEGENDARY: '',
            _loaded: false,
            _error: null
        };
        console.log('✅ window.__ENV__ initialized');
    } catch (e) {
        console.error('❌ Failed to initialize window.__ENV__:', e);
    }
})();

// Load configuration from API
(async function loadConfig() {
    try {
        var hostname = window.location.hostname;
        var isLocalhost = hostname === 'localhost' || hostname === '127.0.0.1';

        console.log('🌐 Current hostname:', hostname);

        if (isLocalhost) {
            console.log('🔧 Development mode - skipping API config fetch');
            window.__ENV__._loaded = true;
            window.__ENV__._error = 'localhost';
            window.dispatchEvent(new CustomEvent('envConfigLoaded', { detail: window.__ENV__ }));
            return;
        }

        console.log('🔄 Fetching config from /api/config...');

        var controller = new AbortController();
        var timeoutId = setTimeout(function() { controller.abort(); }, 8000);

        var response = await fetch('/api/config', {
            signal: controller.signal,
            headers: { 'Accept': 'application/json' }
        });

        clearTimeout(timeoutId);

        if (!response.ok) {
            throw new Error('Config API returned ' + response.status);
        }

        var config = await response.json();
        console.log('📦 Config received:', Object.keys(config).join(', '));

        // Update window.__ENV__ with fetched values
        Object.keys(config).forEach(function(key) {
            window.__ENV__[key] = config[key];
        });
        window.__ENV__._loaded = true;
        window.__ENV__._error = null;

        console.log('✅ Environment config loaded from API');
        console.log('   SUPABASE_URL:', window.__ENV__.SUPABASE_URL ? '✓ Set' : '✗ Missing');
        console.log('   SUPABASE_ANON_KEY:', window.__ENV__.SUPABASE_ANON_KEY ? '✓ Set' : '✗ Missing');

        window.dispatchEvent(new CustomEvent('envConfigLoaded', { detail: window.__ENV__ }));

    } catch (error) {
        console.error('❌ Error loading config:', error.message);
        window.__ENV__._loaded = true;
        window.__ENV__._error = error.message;
        window.dispatchEvent(new CustomEvent('envConfigLoaded', { detail: window.__ENV__ }));
    }
})();
`;

// Write to env-config.js
const outputPath = path.join(__dirname, 'env-config.js');
fs.writeFileSync(outputPath, configContent);

console.log('✅ env-config.js generated successfully');
