#!/usr/bin/env node
/**
 * BUILD-TIME ENVIRONMENT VARIABLE INJECTION
 *
 * This script runs during Vercel build to inject environment variables
 * directly into env-config.js. Values are JSON.stringify'd to handle
 * special characters safely.
 */

const fs = require('fs');
const path = require('path');

// Helper to clean env vars (remove whitespace, newlines)
const clean = (val) => (val || '').replace(/[\s\n\r]+/g, '').trim();

// Read environment variables (set in Vercel dashboard)
const config = {
    SUPABASE_URL: clean(process.env.SUPABASE_URL),
    SUPABASE_ANON_KEY: clean(process.env.SUPABASE_ANON_KEY),
    STRIPE_PUBLIC_KEY: clean(process.env.STRIPE_PUBLIC_KEY),
    STRIPE_LINK_BASIC: clean(process.env.STRIPE_LINK_BASIC),
    STRIPE_LINK_ADVANCED: clean(process.env.STRIPE_LINK_ADVANCED),
    STRIPE_LINK_PREMIUM: clean(process.env.STRIPE_LINK_PREMIUM),
    STRIPE_PRICE_INSTANT: clean(process.env.STRIPE_PRICE_INSTANT),
    STRIPE_PRICE_PRECISION: clean(process.env.STRIPE_PRICE_PRECISION),
    STRIPE_PRICE_LEGENDARY: clean(process.env.STRIPE_PRICE_LEGENDARY)
};

// Generate env-config.js with values injected at build time
// Using JSON.stringify ensures special characters are properly escaped
const configContent = `// Environment configuration for LuvLang Mastering
// AUTO-GENERATED by build-env.js at build time
// Build: ${new Date().toISOString()}
// DO NOT EDIT - changes will be overwritten on next deploy

window.__ENV__ = {
    SUPABASE_URL: ${JSON.stringify(config.SUPABASE_URL)},
    SUPABASE_ANON_KEY: ${JSON.stringify(config.SUPABASE_ANON_KEY)},
    STRIPE_PUBLIC_KEY: ${JSON.stringify(config.STRIPE_PUBLIC_KEY)},
    STRIPE_LINK_BASIC: ${JSON.stringify(config.STRIPE_LINK_BASIC)},
    STRIPE_LINK_ADVANCED: ${JSON.stringify(config.STRIPE_LINK_ADVANCED)},
    STRIPE_LINK_PREMIUM: ${JSON.stringify(config.STRIPE_LINK_PREMIUM)},
    STRIPE_PRICE_INSTANT: ${JSON.stringify(config.STRIPE_PRICE_INSTANT)},
    STRIPE_PRICE_PRECISION: ${JSON.stringify(config.STRIPE_PRICE_PRECISION)},
    STRIPE_PRICE_LEGENDARY: ${JSON.stringify(config.STRIPE_PRICE_LEGENDARY)},
    _loaded: true,
    _error: null
};

// Dispatch event so other scripts know config is ready
window.dispatchEvent(new CustomEvent('envConfigLoaded', { detail: window.__ENV__ }));
`;

// Write to env-config.js
const outputPath = path.join(__dirname, 'env-config.js');
fs.writeFileSync(outputPath, configContent);

// Validate
if (!config.SUPABASE_URL || !config.SUPABASE_ANON_KEY) {
    console.warn('⚠️  Warning: Missing Supabase credentials');
    console.warn('   Set SUPABASE_URL and SUPABASE_ANON_KEY in Vercel Environment Variables');
}
