// Environment configuration for LuvLang Mastering
// AUTO-GENERATED by build-env.js at build time
// Build: 2026-02-03T04:43:37.949Z
// DO NOT EDIT - changes will be overwritten on next deploy

window.__ENV__ = {
    SUPABASE_URL: "",
    SUPABASE_ANON_KEY: "",
    STRIPE_PUBLIC_KEY: "",
    STRIPE_LINK_BASIC: "",
    STRIPE_LINK_ADVANCED: "",
    STRIPE_LINK_PREMIUM: "",
    STRIPE_PRICE_INSTANT: "",
    STRIPE_PRICE_PRECISION: "",
    STRIPE_PRICE_LEGENDARY: "",
    _loaded: true,
    _error: null
};

// Dispatch event so other scripts know config is ready
window.dispatchEvent(new CustomEvent('envConfigLoaded', { detail: window.__ENV__ }));
