// Environment configuration for LuvLang Mastering
// AUTO-GENERATED by build-env.js - Fetches config from /api/config
// Build time: 2026-02-03T04:38:04.275Z

console.log('📦 env-config.js loaded');

// Initialize global config object
(function() {
    try {
        window.__ENV__ = {
            SUPABASE_URL: '',
            SUPABASE_ANON_KEY: '',
            STRIPE_PUBLIC_KEY: '',
            STRIPE_LINK_BASIC: '',
            STRIPE_LINK_ADVANCED: '',
            STRIPE_LINK_PREMIUM: '',
            STRIPE_PRICE_INSTANT: '',
            STRIPE_PRICE_PRECISION: '',
            STRIPE_PRICE_LEGENDARY: '',
            _loaded: false,
            _error: null
        };
        console.log('✅ window.__ENV__ initialized');
    } catch (e) {
        console.error('❌ Failed to initialize window.__ENV__:', e);
    }
})();

// Load configuration from API
(async function loadConfig() {
    try {
        var hostname = window.location.hostname;
        var isLocalhost = hostname === 'localhost' || hostname === '127.0.0.1';

        console.log('🌐 Current hostname:', hostname);

        if (isLocalhost) {
            console.log('🔧 Development mode - skipping API config fetch');
            window.__ENV__._loaded = true;
            window.__ENV__._error = 'localhost';
            window.dispatchEvent(new CustomEvent('envConfigLoaded', { detail: window.__ENV__ }));
            return;
        }

        console.log('🔄 Fetching config from /api/config...');

        var controller = new AbortController();
        var timeoutId = setTimeout(function() { controller.abort(); }, 8000);

        var response = await fetch('/api/config', {
            signal: controller.signal,
            headers: { 'Accept': 'application/json' }
        });

        clearTimeout(timeoutId);

        if (!response.ok) {
            throw new Error('Config API returned ' + response.status);
        }

        var config = await response.json();
        console.log('📦 Config received:', Object.keys(config).join(', '));

        // Update window.__ENV__ with fetched values
        Object.keys(config).forEach(function(key) {
            window.__ENV__[key] = config[key];
        });
        window.__ENV__._loaded = true;
        window.__ENV__._error = null;

        console.log('✅ Environment config loaded from API');
        console.log('   SUPABASE_URL:', window.__ENV__.SUPABASE_URL ? '✓ Set' : '✗ Missing');
        console.log('   SUPABASE_ANON_KEY:', window.__ENV__.SUPABASE_ANON_KEY ? '✓ Set' : '✗ Missing');

        window.dispatchEvent(new CustomEvent('envConfigLoaded', { detail: window.__ENV__ }));

    } catch (error) {
        console.error('❌ Error loading config:', error.message);
        window.__ENV__._loaded = true;
        window.__ENV__._error = error.message;
        window.dispatchEvent(new CustomEvent('envConfigLoaded', { detail: window.__ENV__ }));
    }
})();
