
project_id = "tzskjzkolyiwhijslqmq"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.app", "http://localhost:5173"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false
secure_email_change_enabled = false
enable_anonymous_sign_ins = false

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true
port = 54323

[studio]
enabled = true
port = 54324
api_url = "http://localhost:54321"

[edge_runtime]
enabled = true
port = 54325

[functions.create-paypal-order]
verify_jwt = true

[functions.capture-paypal-payment]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = true

[functions.send-match-notification]
verify_jwt = true

[functions.send-message-notification]
verify_jwt = true

[functions.send-daily-matches]
verify_jwt = true

[functions.send-profile-view-notification]
verify_jwt = true

[functions.send-reengagement-email]
verify_jwt = true

[functions.send-password-reset]
verify_jwt = false
